application: noted-tesla-574
version: 6
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /_ah/mail/snippets@.*noted-tesla-574\.appspotmail\.com
  script: receive_email.py
  login: admin

- url: /static
  static_dir : static

- url: .*
  script: main.py
  secure: always

inbound_services:
- mail

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- remote_api: on
